//! `Handler`: the trait that lets an ordinary `async fn` be a route handler,
//! *regardless of how many extractor arguments it takes*.
//!
//! The goal is to accept all of these as handlers:
//!
//! ```ignore
//! async fn a() -> &'static str { "hi" }
//! async fn b(State(s): State<Db>) -> Json<Stats> { ... }
//! async fn c(Path(id): Path<u64>, Json(body): Json<NewTodo>) -> impl IntoResponse { ... }
//! ```
//!
//! They have different arities and different argument types, yet the router
//! must store them uniformly. Two type-system tools make that work:
//!
//! 1. **A blanket impl per arity, generated by a macro.** We can't be generic
//!    over "a function of N arguments," so we write one `impl Handler` for
//!    0 args, 1 arg, 2 args, … via [`macro_rules!`]. axum does exactly this.
//!    The argument types appear as generic params `T1, T2, …`, each bounded by
//!    [`FromRequestParts`] except the last, which is the body-consuming
//!    [`FromRequest`].
//!
//! 2. **Type erasure into [`BoxedHandler`].** Once a concrete function proves
//!    it implements `Handler`, we box it behind a trait object so every route,
//!    whatever its signature, has the same stored type.

use crate::body::Body;
use crate::extract::{FromRequest, FromRequestParts};
use crate::response::IntoResponse;
use bytes::Bytes;
use http::{Request, Response};
use std::future::Future;
use std::pin::Pin;

/// A boxed, `Send` future yielding a fully-built response. Every handler call,
/// no matter the original signature, funnels into one of these.
pub type BoxFuture = Pin<Box<dyn Future<Output = Response<Body>> + Send>>;

/// Implemented (via the macro below) by every `async fn` whose arguments are
/// extractors and whose return type is [`IntoResponse`]. `T` is a phantom tuple
/// of the argument types + coherence marker; `S` is the app state.
pub trait Handler<T, S>: Clone + Send + Sync + Sized + 'static {
    fn call(self, req: Request<Bytes>, state: S) -> BoxFuture;
}

/// A type-erased handler bound to its state: the uniform thing a route stores.
/// Cloned cheaply per request (it's an `Arc` inside).
#[derive(Clone)]
pub struct BoxedHandler {
    #[allow(clippy::type_complexity)]
    inner: std::sync::Arc<dyn Fn(Request<Bytes>) -> BoxFuture + Send + Sync>,
}

impl BoxedHandler {
    /// Erase a concrete `Handler` + its state into the uniform stored form.
    pub fn new<H, T, S>(handler: H, state: S) -> Self
    where
        H: Handler<T, S>,
        S: Clone + Send + Sync + 'static,
        T: 'static,
    {
        BoxedHandler {
            inner: std::sync::Arc::new(move |req| {
                handler.clone().call(req, state.clone())
            }),
        }
    }

    /// Run the handler against a request whose body is already buffered.
    pub fn call(&self, req: Request<Bytes>) -> BoxFuture {
        (self.inner)(req)
    }
}

/// Generate `impl Handler` for a function of N arguments. The first N-1 are
/// `FromRequestParts` (head only); the last is `FromRequest` (may take the
/// body). Each generated impl splits the request, runs the extractors in order,
/// and on any rejection returns that rejection *as the response* — short-
/// circuiting exactly like `?` would.
macro_rules! impl_handler {
    ( $($ty:ident),* ; $last:ident ) => {
        #[allow(non_snake_case, unused_mut, unused_variables)]
        impl<F, Fut, S, Marker, $($ty,)* $last> Handler<(Marker, $($ty,)* $last,), S> for F
        where
            F: FnOnce($($ty,)* $last) -> Fut + Clone + Send + Sync + 'static,
            Fut: Future + Send + 'static,
            Fut::Output: IntoResponse,
            S: Send + Sync + 'static,
            $( $ty: FromRequestParts<S> + Send, )*
            $last: FromRequest<S, Marker> + Send,
        {
            fn call(self, req: Request<Bytes>, state: S) -> BoxFuture {
                Box::pin(async move {
                    let (mut parts, body) = req.into_parts();
                    $(
                        let $ty = match $ty::from_request_parts(&mut parts, &state) {
                            Ok(value) => value,
                            Err(rejection) => return rejection.into_response(),
                        };
                    )*
                    let req = Request::from_parts(parts, body);
                    let $last = match $last::from_request(req, &state) {
                        Ok(value) => value,
                        Err(rejection) => return rejection.into_response(),
                    };
                    self($($ty,)* $last).await.into_response()
                })
            }
        }
    };
}

// Arity 1 through 5: the last named type is the body-consuming extractor.
impl_handler!(; T1);
impl_handler!(T1; T2);
impl_handler!(T1, T2; T3);
impl_handler!(T1, T2, T3; T4);
impl_handler!(T1, T2, T3, T4; T5);

// Arity 0 is special-cased: no extractors at all, so nothing touches the body.
#[allow(non_snake_case)]
impl<F, Fut, S> Handler<((),), S> for F
where
    F: FnOnce() -> Fut + Clone + Send + Sync + 'static,
    Fut: Future + Send + 'static,
    Fut::Output: IntoResponse,
    S: Send + Sync + 'static,
{
    fn call(self, _req: Request<Bytes>, _state: S) -> BoxFuture {
        Box::pin(async move { self().await.into_response() })
    }
}
